### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by hvisage** [seth-brown/timewarp#5]
Have a situation where I need to make space for a "sudden" set of new big files (several Gigabytes) and need something like 24GB with only 14GB available for a TimeMachine backup.

First run of timewarp (default settigns) didn't remove anything as it's threshold is set for ~1GB only.
I've upped the threshold to 10GB, and it did remove a single backup set which relieved 13GB, but still I need and extra 10GB space so I upped the threshold to 20GB, and then it threw this error:

`BlackYos% ./timewarp.py hv-warp.json
# Time Warp is running in **SAFE MODE**

The following backups would have been deleted:

Traceback (most recent call last):
  File "./timewarp.py", line 230, in <module>
    main(sys.argv[1])
  File "./timewarp.py", line 227, in main
    handler(**config)
  File "./timewarp.py", line 209, in handler
    ave_size = float(free) / len(bups)
ZeroDivisionError: float division by zero`

`BlackYos% cat timewarp.log
2016-06-09 14:17:19 /Volumes/Time Machine Backups/Backups.backupdb/BlackYos/2016-06-06-185750
BlackYos% cat hv-warp.json
{
    "mode": "safe",
    "volume": "/Volumes/Time Machine Backups/Backups.backupdb/BlackYos/",
    "threshold": 20480,
    "log": "timewarp.log"
}`

What would be the cause/reason for this error?

**Comment by drbunsen** [comment]
Thanks for the information. I could not reproduce your issue, but it looks like you are getting a divide by zero error because you either have no backups in the specified directory or perhaps you have misconfigured the volume destination in your config file.

Can you see what value you're getting for `len(bups)` on line 209? Whatever the cause, that seems to be your issue.

**Comment by hvisage** [comment]
<blush>
Yes, that was the problem: no other "valid" and finished backup.... had to redo that backup volume 

Thanks!
